services:
  web:
    build: .
    container_name: django_web
    env_file:
      - .env
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
