# Generated by Django 5.2.6 on 2025-09-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notification_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_booked', 'Appointment Booked'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_cancelled_by_doctor', 'Appointment Cancelled by Doctor'), ('refund_processed', 'Refund Processed'), ('wallet_funded', 'Wallet Funded'), ('wallet_funding_approved', 'Wallet Funding Approved'), ('wallet_funding_rejected', 'Wallet Funding Rejected'), ('day_off_approved', 'Day Off Approved'), ('day_off_rejected', 'Day Off Rejected'), ('profile_change_approved', 'Profile Change Approved'), ('profile_change_rejected', 'Profile Change Rejected'), ('general', 'General')], max_length=50),
        ),
    ]
