# Generated by Django 5.2.6 on 2025-09-22 02:35

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctoravailability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Whether the doctor's credentials have been verified"),
        ),
        migrations.AddField(
            model_name='doctor',
            name='verification_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending Verification'),
                    ('verified', 'Verified'),
                    ('rejected', 'Rejected'),
                    ('suspended', 'Suspended'),
                ],
                default='pending',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='doctor',
            name='verification_notes',
            field=models.TextField(blank=True, help_text="Admin notes about verification", null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='verified_by',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'is_staff': True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='verified_doctors',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
