# Generated by Django 5.2.6 on 2025-09-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_doctoravailability_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='rate',
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Doctor's average rating from reviews", max_digits=3),
        ),
    ]
